parameters:
    cache_tags.invalidator.class:               lbarulski\CacheTagsBundle\Invalidator\Invalidator
    cache_tags.invalidaotr.repository.class:    lbarulski\CacheTagsBundle\Service\Repository
    cache_tags.invalidator.proxy.manager.class: lbarulski\CacheTagsBundle\Invalidator\Proxy\Manager
    cache_tags.invalidator.proxy.varnish.class: lbarulski\CacheTagsBundle\Invalidator\Proxy\Varnish

services:
    cache_tags.invalidator:
        class:      %cache_tags.invalidator.class%
        arguments:  ["@cache_tags.invalidator.repository"]

    cache_tags.invalidator.proxy.manager:
        class:      %cache_tags.invalidator.proxy.manager.class%

    cache_tags.invalidator.repository:
        class:      %cache_tags.invalidaotr.repository.class%

    cache_tags.invalidator.proxy.varnish:
        class:      %cache_tags.invalidator.proxy.varnish.class%
        abstract:   true
        public:     false
        tags:
            - { name: cache_tag.invalidator.proxy }
